export const ADO_PROJECTS = [
  { name: "AABITDigital", description: "Agile board to track Business Integration Team and Digital work" },
  { name: "AAFM-ADO-POC", description: "Proof-of-concept for AAFM engineers" },
  { name: "AAFM-ARCH-POC", description: "Architecture POCs and sandbox" },
  { name: "AAFMDbAdminRes", description: "Database Schema Changes & DBA Projects" },
  { name: "AAFMDevOps", description: "TRTA Development Operations Team" },
  { name: "AAFMProjectManagement", description: "Project Management & Operations" },
  { name: "AAFMReleaseManagement", description: "AAFM Release Management team" },
  { name: "AccountingCS", description: "Accounting CS codebase" },
  { name: "Archive", description: "" },
  { name: "ATPA Scale Testing", description: "" },
  { name: "ATPA-Architecture", description: "ATPA Architecture team projects" },
  { name: "AuditDevOps", description: "Audit DevOps" },
  { name: "CoCounsel Tax Accounting and Audit", description: "Materia / CoCounsel Tax Accounting and Audit" },
  { name: "Content", description: "TR product and account management content" },
  { name: "CSProfessionalCloud", description: "Cloud hosted APIs for CS Professional Suite" },
  { name: "DominioDevOps", description: "Scripts for DominioWeb platform and infrastructure" },
  { name: "Exalate Extension Workshop - Pagero TaxTrade", description: "Exalate extension configuration workshops" },
  { name: "FrontEnd-Center-of-Enablement", description: "Developer experience improvements" },
  { name: "HyperRenta", description: "" },
  { name: "MISDevelopment", description: "" },
  { name: "MISTechOps", description: "MIS TechOps team work tracking" },
  { name: "Sandbox", description: "Sandbox for testing process template changes" },
  { name: "SourceArchive", description: "Read-only copies of legacy source" },
  { name: "SurePrepDevOps", description: "SurePrep Development Operations and Release Management" },
  { name: "SurePrepInnovation", description: "Projects for SurePrep Innovation team" },
  { name: "SurePrep Testing Project", description: "" },
  { name: "TAPDigital", description: "Tax & Accounting Professional Digital Team" },
  { name: "TaxProf", description: "Tax & Accounting Professionals Software development" },
  { name: "TaxSpec", description: "Tax Specialist project" },
  { name: "TaxTrade", description: "Tax and Trade Software Development" },
  { name: "TaxTradeOperations", description: "CIO Service Management SDM and ETS" },
  { name: "Test Rules", description: "" },
  { name: "TR Shared Query Access", description: "Shared Query Management access" },
];
